---
- name: Fail if cluster_name is not defined
  fail:
    msg: cluster_name must be defined
  when: cluster_name is not defined

- name: Load cluster main vars
  include_vars:
    file: "{{ playbook_dir }}/config/cluster/{{ cluster_name }}/vars/main.yml"
    name: _config_main

- name: Load default vars
  include_vars:
    dir: "{{ playbook_dir }}/config/default/vars"
    files_matching: '[a-z0-9].*\.(json|ya?ml)$'

- name: Load cloud provider vars
  include_vars:
    dir: "{{ playbook_dir }}/config/cloud_provider/{{ _config_main.cloud_provider }}/vars"
    files_matching: '[a-z0-9].*\.(json|ya?ml)$'

- name: Load cloud region vars
  include_vars:
    dir: "{{ playbook_dir }}/config/cloud_region/{{ _config_main.cloud_region }}/vars"
    files_matching: '[a-z0-9].*\.(json|ya?ml)$'

- name: Load cluster vars
  include_vars:
    dir: "{{ playbook_dir }}/config/cluster/{{ cluster_name }}/vars"
    files_matching: '^[a-zA-Z0-9].*\.(json|ya?ml)$'

- name: Load dynamic vars
  include_tasks: "{{ dynamic_vars_file.src }}"
  with_filetree:
  - config/dynamic/
  loop_control:
    loop_var: dynamic_vars_file
  when:
    dynamic_vars_file.path is match('.*\.(ya?ml|json)$')
