---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    terraform_dir: "{{ playbook_dir }}/terraform"
  tasks:
  - name: Load cluster config
    import_tasks: load-config.yml
  - name: Include terraform role
    include_role:
      name: "{{ cloud_provider }}-terraform"
